version: "3.8"

services:
  redis-media-converter:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  server-media-converter:
    build: .
    container_name: media-server
    depends_on:
      - redis
    environment:
      - AUTH_TOKEN= # Change this password if the api is exposed outside the docker network created
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["gunicorn", "--worker-class", "gevent", "--workers", "3", "--bind", "0.0.0.0:5095", "wsgi:app"]
    restart: unless-stopped

  converter-media-converter:
    build: .
    container_name: media-converter
    depends_on:
      - redis
    environment:
      - IMAGE_TARGET_WIDTH=1024
      - IMAGE_TARGET_HEIGHT=1024
      - IMAGE_BG_COLOR=#FFFFFF
      - AUDIO_BITRATE=192k
      - LOCK_TTL_SECONDS=600
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["python", "converter.py"]
    restart: unless-stopped

  caddy-media-converter:
    image: caddy:2
    container_name: caddy
    depends_on:
      - server-media-converter
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  redis-data:
  caddy_data:
  caddy_config: