version: "3.8"

services:
  redis-media-converter:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  server-media-converter:
    build: .
    container_name: media-server
    depends_on:
      - redis-media-converter
    environment:
      - AUTH_TOKEN=change_me # Change this password 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["gunicorn", "--worker-class", "gevent", "--workers", "3", "--bind", "0.0.0.0:5095", "wsgi:app"]
    restart: unless-stopped
    ports:
      - "5095:5095"

  converter-media-converter:
    build: .
    container_name: media-converter
    depends_on:
      - redis-media-converter
    environment:
      - IMAGE_TARGET_WIDTH=1024
      - IMAGE_TARGET_HEIGHT=1024
      - IMAGE_BG_COLOR=#FFFFFF
      - AUDIO_BITRATE=192k
      - LOCK_TTL_SECONDS=600
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["python", "converter.py"]
    restart: unless-stopped

volumes:
  redis-data: